import {execute,parseToken} from './engine.js';
import {LEVELS,getLevel,DEFAULTS,cleanConfig,buildProgram,validateLevel} from './levels.js';
import {createStore,normalizeState} from './storage.js';
import {attachDrag} from './drag.js';
const $=s=>document.querySelector(s),clone=x=>JSON.parse(JSON.stringify(x)),esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let storage;try{storage=window.localStorage}catch{storage={getItem(){throw Error()},setItem(){throw Error()},removeItem(){throw Error()}}}
const store=createStore(storage),loaded=store.load();let state=loaded.state,warning=loaded.warning;
let stage=readStage(),caseIndex=0,runResult=null,cursor=0,timer=null,feedback=null,mobilePanel='mission',proofChoice='000',proofMessage='',selectedCard=null;
let dragController;
const labels={rotate:'왼쪽으로 한 칸 회전',flip:'첫 칸 반전',guard:'모두 꺼졌으면 마지막 칸 켜기',read:'다음 신호 읽기',emit:'복원한 신호 보내기',init:'충전량을 0으로',charge:'켜진 칸 수만큼 충전',lightLast:'마지막 칸 켜기',call:'복원 함수 호출',stopIfEnd:'종료 표지면 반복 끝내기'};
function readStage(){const n=Number(location.hash.match(/^#stage-(\d+)$/)?.[1]||1);return n>=1&&n<=8?n:1}
function progress(){return state.progress[stage]}
function level(){return getLevel(stage)}
function sample(){return level().cases[caseIndex]}
function save(){const r=store.save(state);if(!r.ok)warning=r.warning}
function stop(){if(timer){clearInterval(timer);timer=null}}
function resetRuntime(){stop();runResult=null;cursor=0;feedback=null}
function getRun(){if(!runResult)runResult=execute(buildProgram(stage,progress().config,sample().channel),sample().input);return runResult}
function snapshot(){return runResult?runResult.trace[cursor]:{position:0,current:null,outputs:[],energy:null,calls:0,stack:[],label:'명령을 조립한 뒤 실행해 보세요',op:'start',step:0,path:''}}
function tokenHTML(value,{small=false,muted=false,active=false}={}){
 if(!value)return `<span class="signal empty ${small?'small':''}" aria-label="신호 대기"><i></i><i></i><i></i><span class="signal-code">대기</span></span>`;
 const t=parseToken(value);if(t.kind==='end')return `<span class="end-token ${muted?'consumed':''}" aria-label="종료 표지"><b>■</b><span>종료</span></span>`;
 return `<span class="signal ${small?'small':''} ${t.kind==='damaged'?'damaged':''} ${muted?'consumed':''} ${active?'current-token':''}" aria-label="${t.kind==='damaged'?'손상':'정상'} 신호 ${t.bits}">${[...t.bits].map(b=>`<i class="${b==='1'?'on':''}"><span>${b}</span></i>`).join('')}<span class="signal-code">${t.kind==='damaged'?'× 손상':t.bits}</span></span>`;
}
function tokensHTML(values,options={}){return values.length?values.map(v=>tokenHTML(v,options)).join(''):'<span class="empty-note">신호 없음</span>'}
function cityHTML(){const coords=[[15,49],[39,26],[68,40],[95,17],[119,37],[147,23],[168,49],[196,29]];return `<svg class="city-map" viewBox="0 0 212 78" aria-label="8개 도시 회로 중 ${LEVELS.filter(l=>state.progress[l.id].completed).length}개 복구"><path d="M15 49H27V26H39H53V40H68H81V17H95H108V37H119H134V23H147H156V49H168H182V29H196" fill="none" stroke="currentColor" stroke-width="1.5"/>${coords.map(([x,y],i)=>`<g class="city-node ${state.progress[i+1].completed?'restored':''} ${stage===i+1?'selected':''}"><rect x="${x-5}" y="${y-5}" width="10" height="10" rx="2"/><text x="${x}" y="${y+20}">${i+1}</text></g>`).join('')}</svg>`}
function render(){
 dragController?.cancel();selectedCard=null;
 const l=level(),p=progress(),done=LEVELS.filter(x=>state.progress[x.id].completed).length;
 document.documentElement.dataset.reduceMotion=state.reduceMotion?'true':'false';
 $('#app').innerHTML=`<header class="topbar"><a class="brand" href="#stage-1" aria-label="신호 복구실 첫 단계"><span class="brand-mark"><i></i><i></i><i></i></span><span>신호 복구실<small>ALGORITHM SIGNAL LAB</small></span></a><div class="topbar-right"><span class="local-badge"><i></i> 로그인 없이, 이 기기에 저장</span><button class="text-button" data-action="teacher">수업 안내 <span>↗</span></button></div></header>
 <main><section class="intro"><div><p class="eyebrow">8개의 회로, 하나의 도시</p><h1>생각을 연결하면,<br class="mobile-only"> 도시가 켜집니다<span class="accent-dot">.</span></h1><p class="intro-description">카드를 끌어 놓고 실행해 보세요. 목표와 같은 신호가 나오면 성공!</p></div><div class="city-progress"><div><span>도시 복구 진행</span><strong>${done}<small> / 8</small></strong></div>${cityHTML()}</div></section>
 <nav class="stage-rail" aria-label="퍼즐 단계">${LEVELS.map(x=>`<a href="#stage-${x.id}" class="stage-link ${x.id===stage?'active':''} ${state.progress[x.id].completed?'complete':''}" ${x.id===stage?'aria-current="step"':''}><span class="stage-number">${state.progress[x.id].completed?'✓':String(x.id).padStart(2,'0')}</span><span>${x.concept}</span><i></i></a>`).join('')}</nav>
 ${warning?`<div class="warning" role="status">${esc(warning)}</div>`:''}
 <div class="workspace-heading"><div><span class="section-index">MISSION ${String(stage).padStart(2,'0')}</span><h2 id="mission-title" tabindex="-1">${l.title}</h2><span class="concept-chip">${l.concept}</span></div><span class="time-note">권장 ${l.minutes}분 · 속도보다 생각</span></div>
 <section class="stage-task" aria-label="지금 해야 할 일"><span>지금 해야 할 일</span><strong>${tasks[stage]}</strong><ol><li>목표 보기</li><li>카드 놓기</li><li>실행 · 정답 확인</li></ol></section>
 <div class="mobile-tabs" role="tablist" aria-label="작업 영역"><button role="tab" data-panel="mission" aria-selected="${mobilePanel==='mission'}">1. 목표</button><button role="tab" data-panel="editor" aria-selected="${mobilePanel==='editor'}">2. 카드 놓기</button><button role="tab" data-panel="lab" aria-selected="${mobilePanel==='lab'}">3. 결과</button></div>
 <div class="workspace" data-mobile-panel="${mobilePanel}"><aside class="mission-panel panel" data-section="mission"><div class="panel-label"><span>01</span> 미션 브리핑</div><h3>${l.mission}</h3><p>${l.note}</p><details class="thinking-prompt"><summary>생각해 볼 질문</summary><p>${l.question}</p></details>${examplesHTML()}<div class="sample-control"><label for="case-select">검증 사례 <span>${caseIndex+1} / ${l.cases.length}</span></label><select id="case-select">${l.cases.map((c,i)=>`<option value="${i}" ${i===caseIndex?'selected':''}>${c.name}</option>`).join('')}</select></div><div class="target-label">도착하는 신호</div><div class="token-row sample-input">${tokensHTML(sample().input,{small:true})}</div><div class="target-label">목표 출력 <span>순서도 같아야 해요</span></div><div class="token-row target-output">${tokensHTML(sample().outputs,{small:true})}</div>${sample().energy!==null?`<div class="target-energy">목표 충전량 <strong>${sample().energy}<small>칸</small></strong></div>`:''}<div class="hint-box"><button class="text-button" data-action="hint">${p.hint===0?'생각의 실마리 보기':p.hint<3?'다음 힌트 보기':'힌트 모두 보기'} <span>${p.hint}/3</span></button>${p.hint?`<p>${l.hints[p.hint-1]}</p>`:'<small>막히면 힌트를 펼쳐 보세요. 감점은 없어요.</small>'}</div><button class="mobile-only button subtle" data-panel="editor">명령 조립하러 가기 →</button></aside>
 <section class="editor-panel panel" data-section="editor"><div class="panel-label"><span>02</span> 명령 조립 <button class="icon-button" data-action="reset-cards" aria-label="기본 카드로 되돌리기" title="기본 카드로 되돌리기">↺</button></div>${quickStartHTML()}<div class="editor-goal"><span>이렇게 나오면 성공</span><div class="token-row">${tokensHTML(sample().outputs,{small:true})}${sample().energy!==null?`<b>⚡ ${sample().energy}칸</b>`:""}</div></div><p class="editor-help">카드의 <b>⠿ 끌기</b>를 잡아 점선 칸에 놓으세요<br><small>또는 카드 선택 → 칸 누르기 · Esc로 취소</small></p><p id="card-status" class="card-status" role="status">${editorReady()?"카드가 준비됐어요. 실행해 보세요.":"아직 빈칸이 있어요. 카드를 놓아 주세요."}</p><div id="editor">${editorHTML()}</div><details class="program-details"><summary>조립한 프로그램</summary><div id="program-preview">${programHTML()}</div></details></section>
 <section class="lab-panel panel" data-section="lab"><div class="panel-label"><span>03</span> 신호 실험실 <span class="live-status">● READY</span></div><div id="lab-view"></div></section></div>
 <div class="control-bar"><div class="control-left"><button class="button primary" data-action="run"><span>▶</span> 실행해 보기</button><button class="button" data-action="step" title="명령 하나만 실행">한 단계 <span>→</span></button><button class="icon-button" data-action="back" aria-label="이전 단계" title="이전 단계">←</button><button class="icon-button" data-action="restart" aria-label="실행 처음부터" title="실행 처음부터">↺</button></div><button class="button check-button" data-action="check">정답 확인 <span>✓</span></button></div>
 <div id="feedback" aria-live="polite"></div>
 <footer><span>정답 하나보다, 정답에 이르는 생각.</span><div><label class="motion-toggle"><input type="checkbox" id="reduce-motion" ${state.reduceMotion?'checked':''}> 동작 줄이기</label><button class="text-button muted" data-action="reset-all">진행 초기화</button></div></footer></main><div class="sr-only" id="announcement" aria-live="polite"></div>
 <dialog id="teacher-dialog" aria-labelledby="teacher-title"><div class="dialog-heading"><span class="eyebrow">TEACHER’S GUIDE</span><button class="icon-button" data-action="close-dialog" aria-label="안내 닫기">×</button></div><h2 id="teacher-title">한 시간, 여덟 번의 발견</h2><p>도입·시연 5분 → 퍼즐 36분 → 정리 5분 → 질문·이동 여유 4분. 정답을 빠르게 찾기보다, 바뀐 신호와 조건을 설명하도록 이끌어 주세요.</p><div class="guide-note">정상 000과 손상 신호는 달라요. 1~3단계는 회전·반전만, 4단계부터는 암전 보정까지 적용해요. 모든 단계는 바로 들어갈 수 있고 이름이나 답안을 서버로 보내지 않아요.</div>${LEVELS.map(x=>`<details><summary>${x.id}. ${x.title} <span>${x.minutes}분</span></summary><p>${x.guide}</p><p class="muted">${x.question}</p></details>`).join('')}<p class="privacy-note">진행은 이 브라우저에만 저장돼요. 다른 기기로 자동 이동하지 않아요. 공개 도움말이므로 학생도 예시 구조를 볼 수 있어요.</p><button class="button primary" data-action="close-dialog">실험실로 돌아가기</button></dialog>
 <dialog id="confirm-dialog" aria-labelledby="confirm-title"><h2 id="confirm-title">정말 초기화할까요?</h2><p id="confirm-copy"></p><div class="dialog-actions"><button class="button" data-action="cancel-reset">취소</button><button class="button danger" id="confirm-reset">초기화</button></div></dialog>`;
 renderLab();renderFeedback();syncRunning();
}
const options={loop:[['once','한 번만 실행'],['three','3번 반복'],['input','입력이 남아 있는 동안']],filter:[['all','모든 신호 통과'],['lit','정상이고 켜진 칸 있음'],['intact','손상 표지가 없음']],guard:[['before','회전·반전 전에 검사'],['after','회전·반전 후에 검사']],init:[['inside','반복할 때마다 0으로'],['before','반복을 시작하기 전에 0으로']],charge:[['before','복원하기 전에 세기'],['after','복원한 뒤에 세기']],callA:[['basic','회전·반전만 실행'],['function','복원 함수 호출']],callB:[['basic','회전·반전만 실행'],['function','복원 함수 호출']],call:[['basic','회전·반전만 실행'],['function','복원 함수 호출']],stop:[['none','종료 검사 안 함'],['inside','정상 신호 조건 안에서 검사'],['before','신호를 읽은 직후 검사']]};
const tasks={1:'두 명령 카드의 순서를 정해 목표와 같은 신호를 만드세요.',2:'신호를 빠짐없이 처리할 반복 카드를 골라 보세요.',3:'× 손상 신호만 걸러 낼 조건 카드를 골라 보세요.',4:'모두 꺼진 신호를 확인할 위치 카드를 골라 보세요.',5:'충전량을 지우는 때와 더하는 때를 정해 보세요.',6:'복원 카드 3장을 정렬하고 두 회선을 함수에 연결하세요.',7:'오류를 보여 주는 신호를 시험한 뒤 조건을 고치세요.',8:'카드 5장을 놓아 종료 표지 앞의 신호만 처리하세요.'};
function editorReady(){const p=progress();return Object.keys(DEFAULTS[stage]).every(k=>k==='order'?p.draft.orderSlots.every(Boolean):p.draft.placed.includes(k))}
function quickStartHTML(){return stage===1&&!progress().completed?`<div class="quick-start"><strong>처음엔 이렇게 해 보세요</strong><p>① 아래 카드의 손잡이를 잡아요<br>② 1번 · 2번 칸에 하나씩 놓아요<br>③ 실행해 보고 목표와 비교해요</p></div>`:''}
function examplesHTML(){return `<details class="command-examples" ${stage===1?'open':''}><summary>카드가 하는 일 보기</summary><p><b>1</b>은 켜짐, <b>0</b>은 꺼짐이에요.</p><div><strong>↶ 왼쪽 회전</strong><span>맨 앞 칸이 맨 뒤로 가요</span><div class="example-signals">${tokenHTML('100',{small:true})}<b>→</b>${tokenHTML('001',{small:true})}</div></div><div><strong>◐ 첫 칸 반전</strong><span>첫 칸만 0 ↔ 1로 바꿔요</span><div class="example-signals">${tokenHTML('100',{small:true})}<b>→</b>${tokenHTML('000',{small:true})}</div></div>${stage>=4?'<p><b>암전 보정</b>은 결과가 000일 때 마지막 칸을 켜서 001로 만들어요.</p>':''}</details>`}
function sourceCard(group,value,title,{placed=false,index=null}={}){return `<div class="command-card ${placed?'placed-card':''}" data-drag-source data-drag-group="${group}" data-card-value="${value}" data-drag-label="${title}"><button class="drag-handle" data-drag-handle aria-label="${title} 끌기" title="잡고 끌어 놓기">⠿<small>끌기</small></button><button class="card-pick" data-card-pick="${group}:${value}" aria-pressed="false"><strong>${title}</strong><small>${placed?'다른 칸으로 옮길 수 있어요':'눌러서 선택할 수도 있어요'}</small></button>${placed&&group==='order'?`<div class="order-moves"><button class="move-card" data-move="${index}" data-direction="-1" aria-label="${title} 위로" ${index===0?'disabled':''}>↑</button><button class="move-card" data-move="${index}" data-direction="1" aria-label="${title} 아래로" ${index===progress().draft.orderSlots.length-1?'disabled':''}>↓</button></div>`:''}</div>`}
function selectCard(key,title){const filled=progress().draft.placed.includes(key),value=progress().config[key];return `<section class="choice-group" aria-label="${title}"><h3>${title}</h3><button class="drop-slot" data-drop-zone data-drop-group="${key}" data-slot="${key}" data-filled="${filled}" aria-label="${title} 카드 놓는 칸"><span class="slot-kicker">${filled?'놓인 카드 · 바꾸려면 새 카드를 놓으세요':'↓ 여기에 카드 한 장 놓기'}</span><strong>${filled?options[key].find(o=>o[0]===value)[1]:'점선 칸'}</strong></button><div class="card-bank" aria-label="${title} 선택 카드">${options[key].map(([v,t])=>sourceCard(key,v,t)).join('')}</div></section>`}
function orderedCards(){const slots=progress().draft.orderSlots;return `<div class="order-builder"><div class="bank-label">사용할 명령 카드 <small>한 장씩 사용해요</small></div><div class="card-bank" aria-label="명령 카드">${DEFAULTS[stage].order.filter(v=>!slots.includes(v)).map(v=>sourceCard('order',v,labels[v])).join('')||'<p class="bank-empty">모든 카드를 놓았어요. 아래에서 순서를 바꿀 수 있어요.</p>'}</div><div class="flow-fixed">${stage===1?'시작 · 다음 신호 읽기':'ƒ 복원 함수 시작'} ↓</div><div class="order-list">${slots.map((v,i)=>`<div class="order-slot ${v?'order-card':''}" data-drop-zone data-drop-group="order"><button class="slot-select" data-slot="order:${i}" data-filled="${Boolean(v)}" aria-label="${i+1}번 명령 칸"><span class="order-num">${i+1}</span><span>${v?'이 칸에 다른 카드 놓기':'여기에 명령 카드 놓기'}</span></button>${v?sourceCard('order',v,labels[v],{placed:true,index:i}):''}</div>`).join('')}</div><div class="flow-fixed">↓ ${stage===1?'끝 · 복원한 신호 보내기':'함수 끝 · 회선으로 돌아가기'}</div></div>`}
function updateSelection(){document.querySelectorAll('[data-card-pick]').forEach(el=>el.setAttribute('aria-pressed',String(Boolean(selectedCard&&el.dataset.cardPick===`${selectedCard.group}:${selectedCard.value}`))));document.querySelectorAll('[data-drop-zone]').forEach(el=>el.classList.toggle('drop-available',Boolean(selectedCard&&el.dataset.dropGroup===selectedCard.group)))}
function cardMessage(text){announce(text);const el=$('#card-status');if(el)el.textContent=text}
function placeCard(card,slot){if(timer||!card||!slot)return false;const [group,indexText]=slot.split(':');if(group!==card.group){cardMessage('이 카드는 같은 제목의 점선 칸에 놓아 주세요.');return false}const p=progress();if(group==='order'){const index=Number(indexText),slots=p.draft.orderSlots;if(!Number.isInteger(index)||index<0||index>=slots.length||!DEFAULTS[stage].order.includes(card.value))return false;const from=slots.indexOf(card.value);if(from===index)return false;const displaced=slots[index];slots[index]=card.value;if(from>=0)slots[from]=displaced;if(slots.every(Boolean))p.config.order=[...slots]}else{if(!Object.hasOwn(DEFAULTS[stage],group)||!options[group]?.some(([v])=>v===card.value))return false;p.config[group]=card.value;if(!p.draft.placed.includes(group))p.draft.placed.push(group)}resetRuntime();save();render();setPanel('editor');document.querySelector(`[data-slot="${slot}"]`)?.focus({preventScroll:true});cardMessage(editorReady()?'카드를 놓았어요. 이제 실행해 보세요.':'카드를 놓았어요. 남은 빈칸도 채워 주세요.');return true}
function editorHTML(){switch(stage){case 1:return orderedCards();case 2:return selectCard('loop','반복 조건');case 3:return selectCard('filter','어떤 신호를 처리할까요?');case 4:return selectCard('guard','암전 보정의 위치');case 5:return selectCard('init','충전량 초기화')+selectCard('charge','켜진 칸을 세는 시점');case 6:return `<div class="function-label">ƒ 복원(신호) <span>함수 정의</span></div>${orderedCards()}${selectCard('callA','회선 A 연결')}${selectCard('callB','회선 B 연결')}`;case 7:return `<div class="counterexample"><span class="card-kicker">먼저 오류를 드러내세요</span><strong>어떤 입력이 반례일까요?</strong><div class="proof-inputs" aria-label="반례 검사 입력">${[['000','정상 000'],['!110','손상 110'],['111','정상 111']].map(([v,t])=>`<button data-proof-choice="${v}" aria-label="${t}" aria-pressed="${v===proofChoice}">${tokenHTML(v,{small:true})}</button>`).join('')}</div><button class="button proof-button" data-action="proof">원래 코드로 반례 검사</button><p id="proof-result" role="status">${proofMessage|| (progress().proof?'✓ 정상 000의 누락을 확인했어요.':'기본 예제는 통과해요. 다른 입력으로 확인해 보세요.')}</p></div>${selectCard('filter','오류가 있는 조건 고치기')}`;case 8:return selectCard('init','충전량 초기화')+selectCard('stop','종료 표지를 검사할 위치')+selectCard('filter','처리할 신호')+selectCard('call','복원 동작')+selectCard('charge','켜진 칸을 세는 시점');}}
function programHTML(){if(!editorReady())return '<p class="program-empty">빈칸을 모두 채우면 프로그램이 여기에 보여요.</p>';const p=buildProgram(stage,progress().config,sample().channel);function nodes(body,path='main'){return body.map((n,i)=>{const at=`${path}.${i}`,title=n.op==='repeat'?(n.mode==='input'?'입력이 남아 있는 동안':'3번 반복'):n.op==='if'?({intact:'손상 표지가 없으면',lit:'정상이고 켜진 칸이 있으면',all:'모든 신호라면',dark:'모두 꺼졌으면'}[n.condition]):labels[n.op];return `<div class="code-line ${['repeat','if'].includes(n.op)?'branch-line':''}" data-path="${at}"><span class="code-dot"></span><span>${title}</span>${['repeat','if'].includes(n.op)?'<small>┐</small>':''}</div>${n.body?`<div class="code-indent">${nodes(n.body,at)}</div>`:''}`}).join('')};return nodes(p.body)+(stage>=6?`<div class="function-outline"><div class="function-label">ƒ 복원(신호)</div>${nodes(p.functions.restore,'function')}</div>`:'')}
function renderLab(){const s=snapshot(),c=sample(),finished=runResult&&cursor===runResult.trace.length-1;$('#lab-view').innerHTML=`<div class="signal-console"><div class="console-heading"><span>LIVE SIGNAL</span><span>${runResult?String(cursor).padStart(2,'0'):'00'} <small>STEP</small></span></div><div class="incoming-line"><span class="console-caption">입력 대기열</span><div class="token-row">${c.input.length?c.input.map((v,i)=>tokenHTML(v,{small:true,muted:i<s.position,active:i===s.position})).join(''):'<span class="empty-note">입력이 없어요</span>'}</div></div><div class="processor"><span class="flow-arrow">↓</span><div class="processor-signal">${tokenHTML(s.current)}</div><div class="active-command">${esc(s.label)}</div>${s.stack.length?'<span class="function-active">ƒ 복원 함수 안에서 실행 중</span>':''}<span class="flow-arrow">↓</span></div><div class="output-line"><span class="console-caption">내 결과 <small>${s.outputs.length}개</small></span><div class="token-row">${tokensHTML(s.outputs,{small:true})}</div></div><div class="goal-compare"><span class="console-caption">목표와 비교해요</span><div class="token-row">${tokensHTML(c.outputs,{small:true})}</div>${c.energy!==null?`<small>목표 충전량 ${c.energy}칸</small>`:""}</div><div class="console-metrics"><span>읽은 입력 <b>${s.position}<small> / ${c.input.length}</small></b></span>${stage>=5?`<span>충전량 <b>${s.energy===null?'—':s.energy}<small>칸</small></b></span>`:'<span>출력 순서 <b>앞 → 뒤</b></span>'}<span>상태 <b>${s.stopped?'종료 표지':finished?runResult.error?'확인 필요':'실행 끝':timer?'실행 중':'대기'}</b></span></div></div>
 <div class="trace-heading"><h3>실행 기록</h3><span>${runResult?'한 줄을 눌러 그 순간으로 이동':'한 단계씩 결과를 따라가 보세요'}</span></div><div class="trace-list" aria-label="실행 기록">${runResult?runResult.trace.map((t,i)=>`<button class="trace-row ${i===cursor?'selected':''}" data-trace="${i}"><span>${String(i).padStart(2,'0')}</span><strong>${esc(t.label)}</strong><small>${t.current?.bits|| (t.current?.kind==='end'?'종료':'—')}${t.energy!==null?' · ⚡'+t.energy:''}</small></button>`).join(''):'<div class="trace-empty"><span>⌁</span><p>실행하면 신호가 변하는 과정이<br>여기에 차곡차곡 기록돼요</p></div>'}</div>${finished&&runResult.error?`<div class="runtime-error" role="status">${esc(runResult.error.message)}</div>`:''}`;
 document.querySelectorAll('[data-path]').forEach(el=>el.classList.toggle('executing',el.dataset.path===s.path));
 const selected=$('.trace-row.selected'),list=$('.trace-list');if(selected&&list)list.scrollTop=Math.max(0,selected.offsetTop-list.offsetTop-list.clientHeight/2);
 const status=$('.live-status');if(status){status.textContent=timer?'● RUNNING':finished?'● COMPLETE':'● READY';status.classList.toggle('is-running',Boolean(timer))}
}
function syncRunning(){const ready=editorReady();const b=$('[data-action="run"]');if(b)b.innerHTML=timer?'<span>Ⅱ</span> 일시정지':'<span>▶</span> 실행해 보기';if(b)b.disabled=!ready;document.querySelectorAll('[data-card-pick],[data-drag-handle],[data-slot],.move-card,#case-select,[data-proof-choice],[data-action="proof"]').forEach(el=>{if(el.classList.contains('move-card')){const i=Number(el.dataset.move),dir=Number(el.dataset.direction);el.disabled=Boolean(timer)||i+dir<0||i+dir>=progress().draft.orderSlots.length}else el.disabled=Boolean(timer)});$('[data-action="back"]').disabled=cursor===0;$('[data-action="step"]').disabled=Boolean(timer)||!ready;$('[data-action="check"]').disabled=!ready;}
function announce(text){$('#announcement').textContent=text}
function setPanel(panel){mobilePanel=panel;$('.workspace').dataset.mobilePanel=panel;document.querySelectorAll('.mobile-tabs [data-panel]').forEach(b=>b.setAttribute('aria-selected',b.dataset.panel===panel))}
function renderFeedback(){const el=$('#feedback');if(!feedback){el.innerHTML='';return}const {passed,results,requirement}=feedback;const count=results.filter(r=>r.passed).length;const first=results.find(r=>!r.passed);let message;if(requirement)message=requirement;else if(passed)message='모든 입력에서 알고리즘이 정확하게 작동했어요.';else if(first?.run.error)message=first.run.error.message;else if(first&&!first.output){let index=0;while(index<first.run.final.outputs.length&&index<first.expected.outputs.length&&first.run.final.outputs[index]===first.expected.outputs[index])index++;message=`${index+1}번째 출력이 목표와 달라요. 해당 순간의 신호와 명령을 확인해 보세요.`;}else if(first&&!first.energy)message='충전량이 달라요. 초기화 위치와 누적 시점을 확인해 보세요.';else message='입력을 처리한 범위나 함수 연결을 확인해 보세요.';const done=LEVELS.filter(l=>state.progress[l.id].completed).length;el.innerHTML=`<section class="feedback ${passed?'success':'try-again'}"><div class="feedback-icon">${passed?'✓':'↻'}</div><div><span class="eyebrow">${passed?'CIRCUIT RESTORED':'KEEP EXPLORING'}</span><h3>${passed?`${level().district} 회로가 켜졌어요`:`${count} / ${results.length} 사례 통과`}</h3><p>${esc(message)}</p></div>${passed&&stage<8?`<a class="button primary" href="#stage-${stage+1}">다음 회로 →</a>`:passed?`<span class="complete-mark">${done===8?'도시 복구 완료':'8단계 완료 · 도시 복구'} ${done} / 8</span>`:'<button class="button" data-action="view-failure">다른 결과 살펴보기</button>'}<details><summary>전체 검사 결과 보기</summary>${results.map((r,i)=>`<button class="result-row ${r.passed?'pass':'fail'}" data-case="${i}"><span>${r.passed?'✓':'×'}</span>${r.name}<small>${r.passed?'통과':'확인하기 →'}</small></button>`).join('')}</details></section>`}
function finishRun(){stop();renderLab();syncRunning();announce(runResult.error?runResult.error.message:'선택한 사례의 실행이 끝났어요. 전체 검사로 모든 사례를 확인하세요.')}
function stepForward(){if(!editorReady())return;getRun();if(cursor<runResult.trace.length-1)cursor++;if(cursor===runResult.trace.length-1)finishRun();else{renderLab();syncRunning()}}
function startRun(){if(!editorReady())return;dragController?.cancel();selectedCard=null;updateSelection();if(timer){stop();renderLab();syncRunning();return}getRun();if(cursor===runResult.trace.length-1)cursor=0;setPanel('lab');if(state.reduceMotion||window.matchMedia('(prefers-reduced-motion: reduce)').matches){cursor=runResult.trace.length-1;finishRun();return}timer=setInterval(stepForward,500);syncRunning();renderLab()}
function check(){if(!editorReady())return;stop();feedback=validateLevel(stage,progress().config,progress().proof);if(feedback.passed){progress().completed=true;save()}const preserved=feedback;render();feedback=preserved;renderFeedback();announce(feedback.passed?'모든 검증 사례를 통과했어요.':`${feedback.results.filter(r=>r.passed).length}개 사례를 통과했어요. 결과를 확인해 보세요.`);$('#feedback').scrollIntoView({behavior:state.reduceMotion?'instant':'smooth',block:'nearest'})}
let pendingReset=null;
function showReset(kind){stop();syncRunning();pendingReset=kind;$('#confirm-copy').textContent=kind==='all'?'이 기기에 저장된 8개 단계의 카드와 완료 기록이 모두 지워져요.':'현재 단계의 카드만 처음 상태로 돌아가요. 이미 완료한 기록은 유지돼요.';$('#confirm-dialog').showModal()}
function applyReset(){if(pendingReset==='all'){const result=store.clear();state=normalizeState(null);if(!result.ok)warning=result.warning;else warning=null}else{progress().config=clone(DEFAULTS[stage]);progress().draft={placed:[],orderSlots:(DEFAULTS[stage].order||[]).map(()=>null)};save()}pendingReset=null;proofMessage='';resetRuntime();render()}
document.addEventListener('click',e=>{
 if(e.target.closest('.skip-link')){e.preventDefault();$('#mission-title').focus();$('#mission-title').scrollIntoView({block:'start'});return}
 const panel=e.target.closest('[data-panel]');if(panel){setPanel(panel.dataset.panel);return}
 const proofInput=e.target.closest('[data-proof-choice]');if(proofInput&&!timer){proofChoice=proofInput.dataset.proofChoice;proofMessage='';render();setPanel('editor');return}
 const pick=e.target.closest('[data-card-pick]');if(pick&&!timer){const[group,value]=pick.dataset.cardPick.split(':');selectedCard=selectedCard?.group===group&&selectedCard?.value===value?null:{group,value};updateSelection();cardMessage(selectedCard?'카드를 선택했어요. 빛나는 점선 칸을 누르세요.':'카드 선택을 취소했어요.');return}
 const slot=e.target.closest('[data-slot]');if(slot&&!timer){if(selectedCard)placeCard(selectedCard,slot.dataset.slot);else cardMessage('먼저 사용할 카드를 고르거나 손잡이를 끌어 놓으세요.');return}
 const move=e.target.closest('[data-move]');if(move&&!timer){const i=Number(move.dataset.move),j=i+Number(move.dataset.direction),arr=progress().draft.orderSlots;if(j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];if(arr.every(Boolean))progress().config.order=[...arr];resetRuntime();save();render();setPanel('editor');document.querySelector(`[data-move="${j}"]:not(:disabled)`)?.focus({preventScroll:true});return}
 const tr=e.target.closest('[data-trace]');if(tr){stop();cursor=Number(tr.dataset.trace);renderLab();syncRunning();return}
 const caseBtn=e.target.closest('[data-case]');if(caseBtn){stop();caseIndex=Number(caseBtn.dataset.case);runResult=null;cursor=0;getRun();cursor=runResult.trace.length-1;render();setPanel('lab');return}
 const action=e.target.closest('[data-action]')?.dataset.action;
 switch(action){case 'run':startRun();break;case 'step':setPanel('lab');stepForward();break;case 'back':stop();cursor=Math.max(0,cursor-1);renderLab();syncRunning();break;case 'restart':stop();runResult=null;cursor=0;renderLab();syncRunning();break;case 'check':check();break;case 'hint':progress().hint=Math.min(3,progress().hint+1);save();render();break;case 'teacher':stop();syncRunning();$('#teacher-dialog').showModal();break;case 'close-dialog':$('#teacher-dialog').close();break;case 'reset-cards':showReset('cards');break;case 'reset-all':showReset('all');break;case 'cancel-reset':pendingReset=null;$('#confirm-dialog').close();break;case 'proof':{const original=execute(buildProgram(7,DEFAULTS[7]),[proofChoice]);if(proofChoice==='000'&&original.final.outputs.length===0){progress().proof=true;proofMessage='✓ 정상 000이 누락됐어요. 목표는 100 · 충전량 1이에요.';save()}else proofMessage='이 입력에서는 오류가 드러나지 않아요. 정상인데 빠지는 신호를 찾아보세요.';render();setPanel('editor');break}case 'view-failure':{const i=feedback?.results.findIndex(r=>!r.passed);if(i>=0){caseIndex=i;runResult=null;getRun();cursor=runResult.trace.length-1;const failed=feedback.results[i];if(!failed.output&&!runResult.error){const expected=sample().outputs;let index=0;while(index<runResult.final.outputs.length&&index<expected.length&&runResult.final.outputs[index]===expected[index])index++;const step=runResult.trace.findIndex(t=>t.op==='emit'&&t.outputs.length===index+1);if(step>=0)cursor=step;}render();setPanel('lab')}else{setPanel('editor');$('#editor').scrollIntoView({block:'nearest'})}break;}}
 if(e.target.closest('#confirm-reset'))applyReset();
});
document.addEventListener('change',e=>{if(e.target.id==='case-select'){stop();caseIndex=Number(e.target.value);runResult=null;cursor=0;render();$('#case-select')?.focus()}else if(e.target.id==='proof-choice'){proofChoice=e.target.value;proofMessage=''}else if(e.target.id==='reduce-motion'){state.reduceMotion=e.target.checked;save();document.documentElement.dataset.reduceMotion=String(state.reduceMotion)}});
window.addEventListener('hashchange',()=>{if(!/^#stage-\d+$/.test(location.hash))return;stage=readStage();caseIndex=0;proofMessage='';proofChoice='000';mobilePanel='mission';resetRuntime();render()});
window.addEventListener('pagehide',()=>{stop();dragController?.cancel()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&selectedCard){selectedCard=null;updateSelection();cardMessage('카드 선택을 취소했어요.')}});
dragController=attachDrag({root:document,canStart:()=>!timer&&!document.querySelector('dialog[open]'),onDrop:(source,target)=>placeCard({group:source.dataset.dragGroup,value:source.dataset.cardValue},target.dataset.slot||target.querySelector('[data-slot]')?.dataset.slot),announce:cardMessage});
render();
